export const SCREEN_RESIZE = 'SCREEN_RESIZE';
export const MAP_BOUNDING_BOX_CHANGED = 'MAP_BOUNDING_BOX_CHANGED';
export const FEATURE_COLLECTION_CHANGED = 'FEATURE_COLLECTION_CHANGED';
export const FEATURE_SELECTION_INDEX_CHANGED = 'FEATURE_SELECTION_INDEX_CHANGED';
export const SET_AUTO_FIT = 'SET_AUTO_FIT';
